### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by betzerra** [betzerra/headlines-iOS#9]
# Option 3
![3](https://www.dropbox.com/s/74pxmhopwdv5xqd/canillitapp_presentacion_3.jpg?dl=1)

# Option 4
![4](https://www.dropbox.com/s/baterlmi384szq1/canillitapp_presentacion_4.jpg?dl=1)

Thoughts?

**Comment by DNAngeluS** [comment]
opt 3

**Comment by pbendersky** [comment]
4️⃣

**Comment by betzerra** [comment]
4️⃣ it is. Thank you everyone.
